package cn.plasticlove.weixinsell.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.util.Date;

/**
 * The type Order master entity.
 *
 * @author Luka
 * @date 2019 /05/30
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class OrderMasterEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.order_id
     *
     *
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyer_name
     *
     *
     */
    private String buyerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyer_phone
     *
     *
     */
    private String buyerPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyer_address
     *
     *
     */
    private String buyerAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyer_openid
     *
     *
     */
    private String buyerOpenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.order_amount
     *
     *
     */
    private BigDecimal orderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.order_status
     *
     *
     */
    private Byte orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.pay_status
     *
     *
     */
    private Byte payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.create_time
     *
     *
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.update_time
     *
     *
     */
    private Date updateTime;

}