package cn.plasticlove.weixinsell.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.util.Date;

/**
 * The type Product info entity.
 *
 * @author Luka
 * @date 2019 /05/30
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class ProductInfoEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_id
     *
     *
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_name
     *
     *
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_price
     *
     *
     */
    private BigDecimal productPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_stock
     *
     *
     */
    private Integer productStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_description
     *
     *
     */
    private String productDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_icon
     *
     *
     */
    private String productIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_status
     *
     *
     */
    private Byte productStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.category_type
     *
     *
     */
    private Integer categoryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.create_time
     *
     *
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.update_time
     *
     *
     */
    private Date updateTime;


}