package cn.plasticlove.weixinsell.dao;

import cn.plasticlove.weixinsell.entity.OrderDetailEntity;

/**
 * The interface Order detail entity mapper.
 */
public interface OrderDetailEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @param detailId the detail id
     * @return the int
     */
    int deleteByPrimaryKey(String detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @param record the record
     * @return the int
     */
    int insert(OrderDetailEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @param record the record
     * @return the int
     */
    int insertSelective(OrderDetailEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @param detailId the detail id
     * @return the order detail entity
     */
    OrderDetailEntity selectByPrimaryKey(String detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @param record the record
     * @return the int
     */
    int updateByPrimaryKeySelective(OrderDetailEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @param record the record
     * @return the int
     */
    int updateByPrimaryKey(OrderDetailEntity record);
}