package cn.plasticlove.weixinsell.dao;

import cn.plasticlove.weixinsell.entity.OrderMasterEntity;

/**
 * The interface Order master entity mapper.
 */
public interface OrderMasterEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @param orderId the order id
     * @return the int
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @param record the record
     * @return the int
     */
    int insert(OrderMasterEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @param record the record
     * @return the int
     */
    int insertSelective(OrderMasterEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @param orderId the order id
     * @return the order master entity
     */
    OrderMasterEntity selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @param record the record
     * @return the int
     */
    int updateByPrimaryKeySelective(OrderMasterEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @param record the record
     * @return the int
     */
    int updateByPrimaryKey(OrderMasterEntity record);
}