package cn.plasticlove.weixinsell.dao;

import cn.plasticlove.weixinsell.entity.ProductCategoryEntity;

/**
 * The interface Product category entity mapper.
 */
public interface ProductCategoryEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @param categoryId the category id
     * @return the int
     */
    int deleteByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @param record the record
     * @return the int
     */
    int insert(ProductCategoryEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @param record the record
     * @return the int
     */
    int insertSelective(ProductCategoryEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @param categoryId the category id
     * @return the product category entity
     */
    ProductCategoryEntity selectByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @param record the record
     * @return the int
     */
    int updateByPrimaryKeySelective(ProductCategoryEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @param record the record
     * @return the int
     */
    int updateByPrimaryKey(ProductCategoryEntity record);
}