package cn.plasticlove.weixinsell.dao;

import cn.plasticlove.weixinsell.entity.ProductInfoEntity;

import java.util.List;

/**
 * The interface Product info entity mapper.
 * @author Luka
 */
public interface ProductInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @param productId the product id
     * @return the int
     */
    int deleteByPrimaryKey(String productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @param record the record
     * @return the int
     */
    int insert(ProductInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @param record the record
     * @return the int
     */
    int insertSelective(ProductInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @param productId the product id
     * @return the product info entity
     */
    ProductInfoEntity selectByPrimaryKey(String productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @param record the record
     * @return the int
     */
    int updateByPrimaryKeySelective(ProductInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @param record the record
     * @return the int
     */
    int updateByPrimaryKey(ProductInfoEntity record);

    /**
     * List product list.
     *
     * @return the list
     */
    List<ProductInfoEntity> listProduct();
}