package cn.plasticlove.weixinsell.dao;

import cn.plasticlove.weixinsell.entity.SellerInfoEntity;

/**
 * The interface Seller info entity mapper.
 */
public interface SellerInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @param id the id
     * @return the int
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @param record the record
     * @return the int
     */
    int insert(SellerInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @param record the record
     * @return the int
     */
    int insertSelective(SellerInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @param id the id
     * @return the seller info entity
     */
    SellerInfoEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @param record the record
     * @return the int
     */
    int updateByPrimaryKeySelective(SellerInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @param record the record
     * @return the int
     */
    int updateByPrimaryKey(SellerInfoEntity record);
}